EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://localhost:8002/eureka
EUREKA_INSTANCE_HOSTNAME: localhost
SIMPLE_MESSAGE_CONVERTER_ALLOWED_LIST_PATTERNS: io.github.khietbt.events.*,io.github.khietbt.*.events.*