server:
  port: ${SERVER_PORT}
spring:
  application:
    name: sesame-config-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT k, v FROM properties AS p WHERE p.application = ? AND p.profile = ? AND p.label = ?
  profiles:
    include: jdbc

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}

management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
