server:
  port: 8001
spring:
  profiles:
    include: native
  cloud:
    config:
      server:
        bootstrap: false
        native:
          searchLocations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS}