services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://host.docker.internal/keycloak
      KC_DB_USERNAME: keycloak_admin
      KC_DB_PASSWORD: keycloak_admin_password
    ports:
      - 8080:8080
      - 9000:9000
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway